# Generated by Django 3.2.7 on 2021-09-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_name',
        ),
        migrations.RemoveField(
            model_name='quizprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizs',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quizs',
            name='modified',
        ),
        migrations.DeleteModel(
            name='AttemptedQuestion',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizProfile',
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='quiz_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizs'),
        ),
    ]
