# Generated by Django 3.2.5 on 2021-07-27 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandupdate',
            name='image',
            field=models.ImageField(upload_to='edustatic/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
