# Generated by Django 3.2.7 on 2021-09-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='uni_name',
            new_name='uniname',
        ),
    ]
