# Generated by Django 3.2.7 on 2021-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0003_alter_institutions_prospectous'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
