# Generated by Django 3.2.5 on 2021-07-30 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=500)),
                ('prospectous', models.FileField(upload_to='edustatic/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'doc', 'docx', 'pdf'])])),
                ('image', models.ImageField(upload_to='edustatic/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('ins_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduskills.city')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=500)),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduskills.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=500)),
                ('Duration', models.CharField(max_length=400)),
                ('fee', models.IntegerField()),
                ('description', models.TextField()),
                ('program_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduskills.programcategory')),
            ],
        ),
        migrations.AddField(
            model_name='programcategory',
            name='level_of_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduskills.studentlevel'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='edustatic/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField()),
                ('last_date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduskills.institutions')),
            ],
        ),
    ]
