# Generated by Django 3.2.5 on 2021-08-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0006_blogs_queries_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='booklet',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Blogname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eduskills.blogs'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='feedback',
            field=models.TextField(),
        ),
    ]
