# Generated by Django 3.2.5 on 2021-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0007_auto_20210815_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebooks',
            name='Booksnotes',
            field=models.CharField(choices=[('Books', 'Books'), ('Notes', 'Notes'), ('PastPapers', 'PastPapers')], default='Books', max_length=20),
        ),
    ]
