# Generated by Django 3.2.5 on 2021-08-16 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0009_auto_20210816_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsToped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('student_class', models.CharField(max_length=600)),
                ('studied_in', models.CharField(max_length=800)),
                ('board_name', models.CharField(max_length=800)),
                ('toped_year', models.IntegerField()),
                ('student_image', models.ImageField(upload_to='edustatic/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField()),
            ],
        ),
    ]
