# Generated by Django 3.2.5 on 2021-08-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0011_freebooks_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebooks',
            name='book_description',
            field=models.TextField(default=''),
        ),
    ]
