# Generated by Django 3.2.5 on 2021-08-19 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduskills', '0012_freebooks_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('From_DateTime', models.DateTimeField()),
                ('To_DateTime', models.DateTimeField()),
                ('body', models.TextField()),
                ('Host_name', models.CharField(max_length=900)),
                ('Contact_info', models.IntegerField()),
                ('Host_Email', models.EmailField(max_length=254)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=700)),
                ('event_image', models.ImageField(upload_to='edustatic/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
    ]
